sudo: false
language: ruby
rvm:
  - 2.2.4
addons:
  ssh_known_hosts: miklb.com
branches:
  only:
  - jekyll
before_install:
  - bash_scripts/install.sh
script:
  - bash_scripts/build.sh
after_script:
- bash_scripts/server_deploy.sh
- bash_scripts/gh_deploy.sh

env:
  global:
  - secure: ebAcMhKL1rhclMjNXO1zvX2JwuvwIcTyIKE7BdvBzOF4tUGj19+E6A3v12QDro+pX8IF2e1X8gck6z035VtRf37O1flWo4+fKWww8AbeHXxYWr+ZJrtqyoaQFtMlbQiKTEEKBGghayzCHQvQU3OmyjAusCoCHUl9Ip1O1dPLgb8r2yvD4Z5FNWFyOV1CbHfoeBkiI1KFHwhBrLtf2YY+FEjgZXe3sGSuILYO7w2Q724dMxSya51vMZuv+Zj8PXNjARa0Prl5rp7Qt4HXI5GOHzWtIpKHLHfU0LS7XrJYPrlg0h1F9dKf/t6Aalx7P09fOfqNu7L+fa6CEW6SPjvnJPuIONwb5OaWYoe6hpAmhXwT6bAYdw3SNwNclRoSss0BVipDXZMSxktvDECUGkZ1lo3E5JvhtIyzPT1ePEYcO5xJieF5DZbTuGj0bEvxSKXWKnmzQK9uPPBwrVEj7jxlM7FpOoMjjQltQhod9oDWQQCuWlVWKqY0OJlgC2KvY5MsMEBkkWcwmj3CjLSz8vxeJ3hS6dnnyC+2SO0PtmgufoMbfCkmOXN/IYZIRKC3AfY30uW9Xmq1dh8yvsYM4nK4QsFE5v3DUvI8vQtXBYCQMUB+wLcHT2BFbRzf7RVbUZTvuAFqprItpNe+Qknk1zmnid+36bWTOqFtECJQ5DxOxCU=
  - secure: SkIv+L0fMCBt6yAAX/+Ljm1j51w8xj58yHItFKN2glZAO6z3+kWFM4tZl9/9Bqg6U0WyRoW4Rbeli4gKtktFx8y9ijZFSAXDB3ODm3sAZ2aZ6sjco/olDpu96exFegQ2oyD2hQWplESmgLqU+XIenIV3ETPisqWAH769ZG2F3MpkHpq7NoxVfDBPhg3bWUB9oC34n0PL4qgH4lyZ2yUs7u77kdYU3EBkmmtj81RQ0ONUpIqTulme+EZryx0E1XR6pSN3zykH586Kbu6p2QidMG1bQlgrGsGeV01chWdQoKU+T1loEBB+yUlWB+m7FT5pozMAOoQX1g7gB85W7aBwvnixjKKsUwliedtGJvDFovSBpPPBk1UuZQy5JYOzkb+DTLrTdq5/n3vw/7JvhpgM4FJqFd8dhlTr8h5cmMNsnyANQNQsCcxx9jnA2SvoNznKlDTYIB42XUh5psGHNxDU7j4O7e39u1/zT8loUtiPY1vJxJoKdb0Bhx5W50lnSQEF2C5be5DLoEoxK4BNWW3sPo+OOPImyqRuugxFhchWh5SUAm9v5n0p/NMNPt00kcSfOAaiPTnDtZj3ph/5e1wAaaueL4HZCHkO5do4viECA2Y7ZtdTyKK7Ac6DhDsuky9bIm9eUICfKQC9BGYShwP69nFy+CB33xn8nALASXbPi54=
  - secure: RhZy3etas4d5siGMhSIkbIQicuf4iqgabugTaLh2R5JIaVSURTE0SAx2u94Xw/qfTsBTWlisSibgYTZP7505fqFo5oWXTv2TLYTnIY2RXjDogeZw1PX+WjNv1uV5ppJ+2bqqL37fpH8avGBQhRtEKN1xj0IH9rryXeeDUqpusPDgPCWR18hmX5A5Rq+UT11nRDy5X/zJSZtWRK80i1GQ4yO8sda16vcq5ON8NuOvUnQ9t1crHTmpZnXT6xBFnEt468iB1uIBt/dKnEiWnqMZBsmCwBeh3Ee/mm0beGOEm/dZWm8rpaJqjUKzYqaEjzJV5ThldX6qEx8NFYISaux0aaYadGknbjAaVOHNw5huElCAvbAB9RgBAgl6T2pKtaetWdabZxI0enGLORupcz/L3br4RlZLlVGY9ddXB9DNOb3vEYEkphj8cSqSNYh2V7W9dp3fyL24n4ATPhMIxxjliB5me9qJrWpbMd9rgqVoEC2k+3Bh95nJ1f7XBNoJKNcp4hVK11lR136Kd5gq/R2D2eFuTg1M0LK7yVgvsNhPLwixVC+DTPaMStRNhw335Eg1TYOA9LikSKJsSTwlpmS7ejtZR/KhwX4LLjGDZLAKVX0FjW8TcQJprH5kld8JjVYKlCs7yonsctb9hP9g6UpmD7W0MNC13c/5K9gA1BfU7iA=
before_install:
  - bash _scripts/install.sh
