# Permalinks
#
permalink: title
paginate: 5

# Setup
title: Miklb's Mindless Ramblings
author: Michael Bishop
author_img: http://cdn.miklb.com/images/profile_4_16.jpg
description:  Chronicling life in a digital world, touching on web dev, food, and a little of everything in between.
url: https://miklb.com
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
baseurl:             ""
timezone:       America/New_York.

twitter_username: miklb
github_username: miklb


logo: public/favicon.png

webmentions: yes

# Plugins
gems:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-gist
 - jekyll-archives

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

highligher: rouge

# Archives
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tags: '/tag/:name/'
