# Permalinks
#
permalink: pretty

# Setup
title: Miklb's Mindless Ramblings
author: Michael Bishop
author_img: http://cdn.miklb.com/images/profile_4_16_sm.png
description:  Chronicling life in a digital world. Touching on web dev, food, and a little of everything in between.
url: https://miklb.com
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
baseurl:             ""
timezone:       America/New_York.

twitter_username: miklb
github_username: miklb


logo: public/favicon.png

webmentions: yes

# Plugins
gems:
 - octopress-paginate
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
 - jekyll-archives
 - jekyll/tagging
 - jekyll-tagging-related_posts
 - jekyll/imgix

exclude:
  - vendor
# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

highligher: rouge

imgix:
  source: cdn.miklb.com

mapbox-token: pk.eyJ1IjoibWlrbGIiLCJhIjoiY2lvMHdva3EyMTl4eHU2bHlidjliazNidSJ9.pZrw_roD2lO_F89wTNRntg
mapid: miklb.03b6j499
# Archives
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    tags: '/tag/:name/'
