# Permalinks
#
permalink: title
paginate: 5


# Setup
title:               Miklb's Mindless Ramblings
tagline:            chronicling life in a digital world
description:
url: miklb.com
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
baseurl:             ""
timezone:       America/New_York.

twitter:
  username: miklb

logo: public/favicon.png
# be sure that you use kramdown as markdown processor
markdown: kramdown

# configure kramdown

# Plugins

gems: [jekyll-gist, jekyll-paginate, jekyll-seo-tag]
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Michael Bishop
  url:               https://twitter.com/miklb
  email:             miklb@miklb.com

# Custom vars
version:             3.0.0
github:
  repo:              https://github.com/poole/hyde
